## Testing another implementation of the web scraping API for the EDGAR DB

In [1]:
import sys, os
import pandas as pd
from edgar import set_identity

sys.path.append('../src')
from fetch_ticker import get_company_ticker


set_identity("David Yeboah davidzahemenyeboah@gmail.com")

[14:44:41] INFO     Identity of the Edgar REST client set to [David Yeboah                              ]8;id=452287;file:///home/zahemen/miniconda3/envs/edgartools/lib/python3.11/site-packages/edgar/core.py\core.py]8;;\:]8;id=97274;file:///home/zahemen/miniconda3/envs/edgartools/lib/python3.11/site-packages/edgar/core.py#166\166]8;;\
                    davidzahemenyeboah@gmail.com]

In [4]:
ticker = get_company_ticker()
if ticker:
    print(f"The ticker for the selected company is: {ticker}")

Multiple matches found:
1. Apple Inc.
2. APPLIED MATERIALS INC /DE
3. AppLovin Corp
4. NetApp, Inc.
5. APPLIED INDUSTRIAL TECHNOLOGIES INC
6. APPFOLIO INC
7. Science Applications International Corp
8. Intapp, Inc.
9. Apple Hospitality REIT, Inc.
10. APPIAN CORP
11. Applied Digital Corp.
12. G III APPAREL GROUP LTD /DE/
13. APPLIED OPTOELECTRONICS, INC.
14. Apple iSports Group, Inc.
15. Rapport Therapeutics, Inc.
16. Cyber App Solutions Corp.
17. MAUI LAND & PINEAPPLE CO INC
18. APPLIED ENERGETICS, INC.
19. Applied Therapeutics, Inc.
20. Harvard Apparatus Regenerative Technology, Inc.
21. CXApp Inc.
22. Intelligent Living Application Group Inc.
23. AppTech Payments Corp.
24. APPLIED DNA SCIENCES INC
25. APPYEA, INC
26. Zapp Electric Vehicles Group Ltd
27. PINEAPPLE EXPRESS CANNABIS Co
28. Pineapple Financial Inc.
29. APPlife Digital Solutions Inc
30. Appsoft Technologies, Inc.
31. METATRON APPS, INC.
32. DELTA APPAREL, INC
33. PINEAPPLE, INC.
34. CODE GREEN APPAREL CORP
35. Sincerity Applied Materials Holdings Corp.
36. Applied UV, Inc.
37. APPLIED ENERGETICS, INC.
38. Zapp Electric Vehicles Group Ltd
39. CXApp Inc.
40. Guru App Factory Corp
41. AppTech Payments Corp.
The ticker for the selected company is: AAPL

In [5]:
from edgar import Company

apple = Company(ticker)
apple

╭────────────────────────────────────────────── 🏢Apple Inc. (AAPL) ──────────────────────────────────────────────╮
│                                                                                                                 │
│                                                                                                                 │
│ ╭───────────────────────────────────────────────── 📋 Entity ─────────────────────────────────────────────────╮ │
│ │                                                                                                             │ │
│ │   CIK   320193   Type   Operating   ○                                                                       │ │
│ │                                                                                                             │ │
│ │                                                                                                             │ │
│ │   Category                  Industry                     Fiscal Year End                                    │ │
│ │  ────────────────────────────────────────────────────────────────────────                                   │ │
│ │   Large accelerated filer   3571: Electronic Computers   Sep 27                                             │ │
│ │                                                                                                             │ │
│ ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │
│ ╭─────────────────────────────────────────────── 📈 Exchanges ────────────────────────────────────────────────╮ │
│ │                                                                                                             │ │
│ │   Exchange   Symbol                                                                                         │ │
│ │  ───────────────────                                                                                        │ │
│ │   Nasdaq     AAPL                                                                                           │ │
│ │                                                                                                             │ │
│ ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │
│ ╭─── 🏢 Business Address ────╮      ╭──── 📫 Mailing Address ────╮     ╭── 📞 Contact Information ──╮           │
│ │ ONE APPLE PARK WAY         │      │ ONE APPLE PARK WAY         │     │                            │           │
│ │ CUPERTINO, CA 95014        │      │ CUPERTINO, CA 95014        │     │   Phone   (408) 996-1010   │           │
│ ╰────────────────────────────╯      ╰────────────────────────────╯     │                            │           │
│                                                                        ╰────────────────────────────╯           │
│ ╭────────────────────────────────────────────── 📜 Former Names ──────────────────────────────────────────────╮ │
│ │                                                                                                             │ │
│ │   APPLE INC                January 2007 to August 2019                                                      │ │
│ │   APPLE COMPUTER INC       January 1994 to January 2007                                                     │ │
│ │   APPLE COMPUTER INC/ FA   July 1997 to July 1997                                                           │ │
│ │                                                                                                             │ │
│ ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────── SEC Entity Data ────────────────────────────────────────────────╯

In [6]:
type(apple)

edgar.entities.EntityData

In [7]:
apple.financials

                Apple Inc. Financials
╭───┬───────────────────────────────────────────────╮
│ 1 │ Cover Page                                    │
│ 2 │ Consolidated Balance Sheets                   │
│ 3 │ Income Statements                             │
│ 4 │ Consolidated Statement of Cash Flows          │
│ 5 │ Consolidated Statement of Shareholders Equity │
│ 6 │ Comprehensive Income Statement                │
╰───┴───────────────────────────────────────────────╯
          Period ending September 28, 2024

In [8]:
apple.former_names

[{'name': 'APPLE INC', 'from': '2007-01-10', 'to': '2019-08-05'},
 {'name': 'APPLE COMPUTER INC', 'from': '1994-01-26', 'to': '2007-01-04'},
 {'name': 'APPLE COMPUTER INC/ FA', 'from': '1997-07-28', 'to': '1997-07-28'}]

In [9]:
filings = apple.get_filings(form="10-K")
filings

╭──────────────────────────────────────── Filings for Apple Inc. [320193] ────────────────────────────────────────╮
│                                                                                                                 │
│        form   filed        accession_number       xbrl                                                          │
│  ──────────────────────────────────────────────────────                                                         │
│   0    10-K   2024-11-01   0000320193-24-000123   ✓                                                             │
│   1    10-K   2023-11-03   0000320193-23-000106   ✓                                                             │
│   2    10-K   2022-10-28   0000320193-22-000108   ✓                                                             │
│   3    10-K   2021-10-29   0000320193-21-000105   ✓                                                             │
│   4    10-K   2020-10-30   0000320193-20-000096   ✓                                                             │
│   5    10-K   2019-10-31   0000320193-19-000119   ✓                                                             │
│   6    10-K   2018-11-05   0000320193-18-000145   ✓                                                             │
│   7    10-K   2017-11-03   0000320193-17-000070   ✓                                                             │
│   8    10-K   2016-10-26   0001628280-16-020309   ✓                                                             │
│   9    10-K   2015-10-28   0001193125-15-356351   ✓                                                             │
│   10   10-K   2014-10-27   0001193125-14-383437   ✓                                                             │
│   11   10-K   2013-10-30   0001193125-13-416534   ✓                                                             │
│   12   10-K   2012-10-31   0001193125-12-444068   ✓                                                             │
│   13   10-K   2011-10-26   0001193125-11-282113   ✓                                                             │
│   14   10-K   2010-10-27   0001193125-10-238044   ✓                                                             │
│   15   10-K   2009-10-27   0001193125-09-214859   ✓                                                             │
│   16   10-K   2008-11-05   0001193125-08-224958                                                                 │
│   17   10-K   2007-11-15   0001047469-07-009340                                                                 │
│   18   10-K   2006-12-29   0001104659-06-084288                                                                 │
│   19   10-K   2005-12-01   0001104659-05-058421                                                                 │
│   20   10-K   2004-12-03   0001047469-04-035975                                                                 │
│   21   10-K   2003-12-19   0001047469-03-041604                                                                 │
│   22   10-K   2002-12-19   0001047469-02-007674                                                                 │
│   23   10-K   2000-12-14   0000912057-00-053623                                                                 │
│   24   10-K   1999-12-22   0000912057-99-010244                                                                 │
│   25   10-K   1997-12-05   0001047469-97-006960                                                                 │
│   26   10-K   1996-12-19   0000320193-96-000023                                                                 │
│   27   10-K   1995-12-19   0000320193-95-000016                                                                 │
│   28   10-K   1994-12-13   0000320193-94-000016                                                                 │
│                                                                                                                 │
│ Showing 29 filings of 29 total                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

In [10]:
filings.to_pandas()

,accession_number,filing_date,reportDate,acceptanceDateTime,act,form,fileNumber,items,size,isXBRL,isInlineXBRL,primaryDocument,primaryDocDescription
0,0000320193-24-000123,2024-11-01,2024-09-28,2024-11-01T06:01:36.000Z,34,10-K,001-36743,,9759333,1,1,aapl-20240928.htm,10-K
1,0000320193-23-000106,2023-11-03,2023-09-30,2023-11-02T18:08:27.000Z,34,10-K,001-36743,,9569569,1,1,aapl-20230930.htm,10-K
2,0000320193-22-000108,2022-10-28,2022-09-24,2022-10-27T18:01:14.000Z,34,10-K,001-36743,,10332356,1,1,aapl-20220924.htm,10-K
3,0000320193-21-000105,2021-10-29,2021-09-25,2021-10-28T18:04:28.000Z,34,10-K,001-36743,,10502096,1,1,aapl-20210925.htm,10-K
4,0000320193-20-000096,2020-10-30,2020-09-26,2020-10-29T18:06:25.000Z,34,10-K,001-36743,,12502600,1,1,aapl-20200926.htm,10-K
5,0000320193-19-000119,2019-10-31,2019-09-28,2019-10-30T18:12:36.000Z,34,10-K,001-36743,,12861616,1,1,a10-k20199282019.htm,10-K
6,0000320193-18-000145,2018-11-05,2018-09-29,2018-11-05T08:01:40.000Z,34,10-K,001-36743,,12275572,1,0,a10-k20189292018.htm,10-K
7,0000320193-17-000070,2017-11-03,2017-09-30,2017-11-03T08:01:37.000Z,34,10-K,001-36743,,14071062,1,0,a10-k20179302017.htm,10-K
8,0001628280-16-020309,2016-10-26,2016-09-24,2016-10-26T16:42:16.000Z,34,10-K,001-36743,,13277662,1,0,a201610-k9242016.htm,10-K
9,0001193125-15-356351,2015-10-28,2015-09-26,2015-10-28T16:31:09.000Z,34,10-K,001-36743,,9594425,1,0,d17062d10k.htm,FORM 10-K
10,0001193125-14-383437,2014-10-27,2014-09-27,2014-10-27T17:11:55.000Z,34,10-K,000-10030,,12082626,1,0,d783162d10k.htm,10-K
11,0001193125-13-416534,2013-10-30,2013-09-28,2013-10-29T20:38:28.000Z,34,10-K,000-10030,,11043722,1,0,d590790d10k.htm,FORM 10-K
12,0001193125-12-444068,2012-10-31,2012-09-29,2012-10-31T17:07:19.000Z,34,10-K,000-10030,,9859755,1,0,d411355d10k.htm,FORM 10-K
13,0001193125-11-282113,2011-10-26,2011-09-24,2011-10-26T16:35:25.000Z,34,10-K,000-10030,,9435428,1,0,d220209d10k.htm,FORM 10-K
14,0001193125-10-238044,2010-10-27,2010-09-25,2010-10-27T16:36:21.000Z,34,10-K,000-10030,,13856661,1,0,d10k.htm,"FOR THE FISCAL YEAR ENDED SEPTEMBER 25, 2010"
15,0001193125-09-214859,2009-10-27,2009-09-26,2009-10-27T16:18:29.000Z,34,10-K,000-10030,,3638340,1,0,d10k.htm,"FOR THE FISCAL YEAR ENDED SEPTEMBER 26, 2009"
16,0001193125-08-224958,2008-11-05,2008-09-27,2008-11-05T06:16:23.000Z,34,10-K,000-10030,,1188704,0,0,d10k.htm,FORM 10-K
17,0001047469-07-009340,2007-11-15,2007-09-29,2007-11-15T16:49:37.000Z,34,10-K,000-10030,,1178091,0,0,a2181030z10-k.htm,10-K
18,0001104659-06-084288,2006-12-29,2006-09-30,2006-12-29T06:05:58.000Z,34,10-K,000-10030,,4280524,0,0,a06-25759_210k.htm,ANNUAL REPORT PURSUANT TO SECTION 13 AND 15(D)
19,0001104659-05-058421,2005-12-01,2005-09-24,2005-11-30T21:22:48.000Z,34,10-K,000-10030,,3185770,0,0,a05-20674_110k.htm,ANNUAL REPORT PURSUANT TO SECTION 13 AND 15(D)
20,0001047469-04-035975,2004-12-03,2004-09-25,2004-12-02T18:05:49.000Z,34,10-K,000-10030,,966203,0,0,a2147337z10-k.htm,10-K
21,0001047469-03-041604,2003-12-19,2003-09-27,2003-12-19T17:25:45.000Z,,10-K,000-10030,,2030692,0,0,a2124888z10-k.htm,10-K
22,0001047469-02-007674,2002-12-19,2002-09-28,2002-12-19T17:20:21.000Z,,10-K,000-10030,,895268,0,0,a2096490z10-k.htm,10-K
23,0000912057-00-053623,2000-12-14,2000-09-30,2000-12-14T00:00:00.000Z,,10-K,000-10030,,310911,0,0,a2032880z10-k.txt,FORM 10-K
24,0000912057-99-010244,1999-12-22,1999-09-25,1999-12-22T00:00:00.000Z,,10-K,000-10030,,502984,0,0,,10-K
25,0001047469-97-006960,1997-12-05,1997-09-26,1997-12-05T00:00:00.000Z,,10-K,000-10030,,639342,0,0,,10-K
26,0000320193-96-000023,1996-12-19,1996-09-27,1996-12-19T00:00:00.000Z,,10-K,000-10030,,271212,0,0,,
27,0000320193-95-000016,1995-12-19,1995-09-29,1995-12-19T00:00:00.000Z,,10-K,000-10030,,232170,0,0,,
28,0000320193-94-000016,1994-12-13,1994-09-30,1994-12-13T00:00:00.000Z,,10-K,000-10030,,240556,0,0,,

In [11]:
latest_10k = filings.latest() # Get the latest N 10-K filings 

latest_10k

╭────────────────────────────────────────── Apple Inc. [320193] 10-K 📊 ──────────────────────────────────────────╮
│ ╭──────────────────────┬────────────╮                                                                           │
│ │ 0000320193-24-000123 │ 2024-11-01 │                                                                           │
│ ╰──────────────────────┴────────────╯                                                                           │
│ ╭───────────────────────────────────────────────────────────────────────────────────────────╮                   │
│ │ Links: 🏠 Homepage 📄 Primary Document 📜 Full Submission Text                            │                   │
│ ├───────────────────────────────────────────────────────────────────────────────────────────┤                   │
│ │ 🏠 https://sec.gov/Archives/edgar/data/320193/0000320193-24-000123-index.html             │                   │
│ │ 📄 https://sec.gov/Archives/edgar/data/320193/000032019324000123/aapl-20240928.htm        │                   │
│ │ 📜 https://sec.gov/Archives/edgar/data/320193/000032019324000123/0000320193-24-000123.txt │                   │
│ ╰───────────────────────────────────────────────────────────────────────────────────────────╯                   │
╰───────────────────────────────── Form 10-K: Annual report for public companies ─────────────────────────────────╯

In [12]:
# Get the 10-K for 2024

tenK_2024 = latest_10k.obj()
tenK_2024.financials

                Apple Inc. Financials
╭───┬───────────────────────────────────────────────╮
│ 1 │ Cover Page                                    │
│ 2 │ Consolidated Balance Sheets                   │
│ 3 │ Income Statements                             │
│ 4 │ Consolidated Statement of Cash Flows          │
│ 5 │ Consolidated Statement of Shareholders Equity │
│ 6 │ Comprehensive Income Statement                │
╰───┴───────────────────────────────────────────────╯
          Period ending September 28, 2024

In [13]:
tenK_2024.items

['Item 1',
 'Item 1A',
 'Item 1B',
 'Item 1C',
 'Item 2',
 'Item 3',
 'Item 4',
 'Item 5',
 'Item 6',
 'Item 7',
 'Item 7A',
 'Item 8',
 'Item 9',
 'Item 9A',
 'Item 9B',
 'Item 9C',
 'Item 10',
 'Item 11',
 'Item 12',
 'Item 13',
 'Item 14',
 'Item 15',
 'Item 16']

In [14]:
print(tenK_2024["Item 2"])

Item 2.    Properties
The Company’s headquarters is located in Cupertino, California. As of September 28, 2024, the Company owned or leased facilities and land for corporate functions, R&D, data centers, retail and other purposes at locations throughout the U.S. and in various places outside the U.S. The Company believes its existing facilities and equipment, which are used by all reportable segments, are in good operating condition and are suitable for the conduct of its business.

So I just noticed this, but we don't actually need to use the argument `latest(n)`, because the function has already been designed to take the data from the last 3 years. Instead, we can just use the default `latest()` and get all the data we need

In [15]:
xbrl_2024 = latest_10k.xbrl()
xbrl_2024

╭───────────────────────────────────────────────────── XBRL ──────────────────────────────────────────────────────╮
│                   XBRL Instance                                                                                 │
│                                                                                                                 │
│   Company      Form   Period               Facts                                                                │
│  ────────────────────────────────────────────────                                                               │
│   Apple Inc.   10-K   September 28, 2024   1,045                                                                │
│                                                                                                                 │
│                           Financial Statements                                                                  │
│                                                                                                                 │
│   Name                                 Accessor                                                                 │
│  ──────────────────────────────────────────────────────────────────────                                         │
│   Balance Sheet                        financials.balance_sheet                                                 │
│   Income Statement                     financials.income                                                        │
│   Cash Flow Statement                  financials.cashflow                                                      │
│   Statement of Changes in Equity       financials.equity                                                        │
│   Statement of Comprehensive Income    financials.comprehensive_income                                          │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

The XBRL Instance gives us an idea on how to fetch the right financial data from the Company object

In [16]:
pd.concat(
    {'Cashflow': apple.financials.cashflow.to_dataframe()}
)

                                                                      2024  \
         label
Cashflow Cash, cash equivalents, and restricted cash and...    29943000000
         Net income                                            93736000000
         Depreciation and amortization                         11445000000
         Share-based compensation expense                      11688000000
         Other                                                 -2266000000
         Accounts receivable, net                              -3788000000
         Vendor non-trade receivables                          -1356000000
         Inventories                                           -1046000000
         Other current and non-current assets                 -11731000000
         Accounts payable                                       6020000000
         Other current and non-current liabilities             15552000000
         Cash generated by operating activities               118254000000
         Purchases of marketable securities                   -48656000000
         Proceeds from maturities of marketable securities     51211000000
         Proceeds from sales of marketable securities          11135000000
         Payments for acquisition of property, plant and...    -9447000000
         Other                                                 -1308000000
         Cash generated by/(used in) investing activities       2935000000
         Payments for taxes related to net share settlem...    -5441000000
         Payments for dividends and dividend equivalents      -15234000000
         Repurchases of common stock                          -94949000000
         Proceeds from issuance of term debt, net                        0
         Repayments of term debt                               -9958000000
         Proceeds from/(Repayments of) commercial paper,...     3960000000
         Other                                                  -361000000
         Cash used in financing activities                   -121983000000
         Increase/(Decrease) in cash, cash equivalents, ...     -794000000
         Cash paid for income taxes, net                       26102000000

                                                                      2023  \
         label
Cashflow Cash, cash equivalents, and restricted cash and...    30737000000
         Net income                                            96995000000
         Depreciation and amortization                         11519000000
         Share-based compensation expense                      10833000000
         Other                                                 -2227000000
         Accounts receivable, net                              -1688000000
         Vendor non-trade receivables                          -1271000000
         Inventories                                           -1618000000
         Other current and non-current assets                  -5684000000
         Accounts payable                                      -1889000000
         Other current and non-current liabilities              3031000000
         Cash generated by operating activities               110543000000
         Purchases of marketable securities                   -29513000000
         Proceeds from maturities of marketable securities     39686000000
         Proceeds from sales of marketable securities           5828000000
         Payments for acquisition of property, plant and...   -10959000000
         Other                                                 -1337000000
         Cash generated by/(used in) investing activities       3705000000
         Payments for taxes related to net share settlem...    -5431000000
         Payments for dividends and dividend equivalents      -15025000000
         Repurchases of common stock                          -77550000000
         Proceeds from issuance of term debt, net               5228000000
         Repayments of term debt                              -11151000000
         Proceeds from/(Repayments of) commercial paper,...    -3978000000
         Other                                                  -581000000
         Cash used in financing activities                   -108488000000
         Increase/(Decrease) in cash, cash equivalents, ...     5760000000
         Cash paid for income taxes, net                       18679000000

                                                                      2022
         label
Cashflow Cash, cash equivalents, and restricted cash and...    24977000000
         Net income                                            99803000000
         Depreciation and amortization                         11104000000
         Share-based compensation expense                       9038000000
         Other                                                 -1006000000
         Accounts receivable, net                              -1823000000
         Vendor non-trade receivables                          -7520000000
         Inventories                                           -1484000000
         Other current and non-current assets                  -6499000000
         Accounts payable                                       9448000000
         Other current and non-current liabilities              6110000000
         Cash generated by operating activities               122151000000
         Purchases of marketable securities                   -76923000000
         Proceeds from maturities of marketable securities     29917000000
         Proceeds from sales of marketable securities          37446000000
         Payments for acquisition of property, plant and...   -10708000000
         Other                                                 -2086000000
         Cash generated by/(used in) investing activities     -22354000000
         Payments for taxes related to net share settlem...    -6223000000
         Payments for dividends and dividend equivalents      -14841000000
         Repurchases of common stock                          -89402000000
         Proceeds from issuance of term debt, net               5465000000
         Repayments of term debt                               -9543000000
         Proceeds from/(Repayments of) commercial paper,...     3955000000
         Other                                                  -160000000
         Cash used in financing activities                   -110749000000
         Increase/(Decrease) in cash, cash equivalents, ...   -10952000000
         Cash paid for income taxes, net                       19573000000

In [17]:
pd.concat(
    {'Income': apple.financials.income.to_dataframe()}
)

                                                          2024           2023  \
       label
Income Net sales                                  391035000000   383285000000
       Products                                   294866000000   298085000000
       Services                                    96169000000    85200000000
       Cost of sales                             -210352000000  -214137000000
       Products                                  -185233000000  -189282000000
       Services                                   -25119000000   -24855000000
       Gross margin                               180683000000   169148000000
       Research and development                    31370000000    29915000000
       Selling, general and administrative         26097000000    24932000000
       Total operating expenses                   -57467000000   -54847000000
       Operating income                           123216000000   114301000000
       Other income/(expense), net                   269000000     -565000000
       Income before provision for income taxes   123485000000   113736000000
       Provision for income taxes                 -29749000000   -16741000000
       Net income                                  93736000000    96995000000
       Basic (in dollars per share)                       6.11           6.16
       Diluted (in dollars per share)                     6.08           6.13
       Basic (in shares)                           15343783000    15744231000
       Diluted (in shares)                         15408095000    15812547000

                                                          2022
       label
Income Net sales                                  394328000000
       Products                                   316199000000
       Services                                    78129000000
       Cost of sales                             -223546000000
       Products                                  -201471000000
       Services                                   -22075000000
       Gross margin                               170782000000
       Research and development                    26251000000
       Selling, general and administrative         25094000000
       Total operating expenses                   -51345000000
       Operating income                           119437000000
       Other income/(expense), net                  -334000000
       Income before provision for income taxes   119103000000
       Provision for income taxes                 -19300000000
       Net income                                  99803000000
       Basic (in dollars per share)                       6.15
       Diluted (in dollars per share)                     6.11
       Basic (in shares)                           16215963000
       Diluted (in shares)                         16325819000

---
 Other Methods

In [20]:
income_df = pd.concat({'Income': apple.financials.income.to_dataframe()})
income_df.head()

                               2024           2023           2022
       label
Income Net sales       391035000000   383285000000   394328000000
       Products        294866000000   298085000000   316199000000
       Services         96169000000    85200000000    78129000000
       Cost of sales  -210352000000  -214137000000  -223546000000
       Products       -185233000000  -189282000000  -201471000000

In [21]:
cashflow_df = pd.concat({'Cashflows': apple.financials.cashflow.to_dataframe()})
cashflow_df.head()

                                                                     2024  \
          label
Cashflows Cash, cash equivalents, and restricted cash and...  29943000000
          Net income                                          93736000000
          Depreciation and amortization                       11445000000
          Share-based compensation expense                    11688000000
          Other                                               -2266000000

                                                                     2023  \
          label
Cashflows Cash, cash equivalents, and restricted cash and...  30737000000
          Net income                                          96995000000
          Depreciation and amortization                       11519000000
          Share-based compensation expense                    10833000000
          Other                                               -2227000000

                                                                     2022
          label
Cashflows Cash, cash equivalents, and restricted cash and...  24977000000
          Net income                                          99803000000
          Depreciation and amortization                       11104000000
          Share-based compensation expense                     9038000000
          Other                                               -1006000000

In [26]:
apple_financial_df = pd.concat([income_df, cashflow_df], axis=0).T
apple_financial_df

             Income                                                           \
label     Net sales      Products     Services  Cost of sales       Products
2024   391035000000  294866000000  96169000000  -210352000000  -185233000000
2023   383285000000  298085000000  85200000000  -214137000000  -189282000000
2022   394328000000  316199000000  78129000000  -223546000000  -201471000000

                                                            \
label      Services  Gross margin Research and development
2024   -25119000000  180683000000              31370000000
2023   -24855000000  169148000000              29915000000
2022   -22075000000  170782000000              26251000000

                                                                    ...  \
label Selling, general and administrative Total operating expenses  ...
2024                          26097000000             -57467000000  ...
2023                          24932000000             -54847000000  ...
2022                          25094000000             -51345000000  ...

                                                                Cashflows  \
label Payments for taxes related to net share settlement of equity awards
2024                                         -5441000000
2023                                         -5431000000
2022                                         -6223000000

                                                       \
label Payments for dividends and dividend equivalents
2024                                     -15234000000
2023                                     -15025000000
2022                                     -14841000000

                                                                            \
label Repurchases of common stock Proceeds from issuance of term debt, net
2024                 -94949000000                                        0
2023                 -77550000000                               5228000000
2022                 -89402000000                               5465000000

                               \
label Repayments of term debt
2024              -9958000000
2023             -11151000000
2022              -9543000000

                                                                       \
label Proceeds from/(Repayments of) commercial paper, net       Other
2024                                          3960000000   -361000000
2023                                         -3978000000   -581000000
2022                                          3955000000   -160000000

                                         \
label Cash used in financing activities
2024                      -121983000000
2023                      -108488000000
2022                      -110749000000

                                                                                               \
label Increase/(Decrease) in cash, cash equivalents, and restricted cash and cash equivalents
2024                                          -794000000
2023                                          5760000000
2022                                        -10952000000


label Cash paid for income taxes, net
2024                      26102000000
2023                      18679000000
2022                      19573000000

[3 rows x 47 columns]

In [31]:
apple_financial_df.to_csv('apple_financials.csv')

In [34]:
pd.read_csv('apple_financials.csv', drop_unnamed=True)

TypeError: read_csv() got an unexpected keyword argument 'drop_unnamed'

In [30]:
display(apple_financial_df.unstack())

           label
Income     Net sales                                                                                2024    391035000000
                                                                                                    2023    383285000000
                                                                                                    2022    394328000000
           Products                                                                                 2024    294866000000
                                                                                                    2023    298085000000
                                                                                                                ...
Cashflows  Increase/(Decrease) in cash, cash equivalents, and restricted cash and cash equivalents  2023      5760000000
                                                                                                    2022    -10952000000
           Cash paid for income taxes, net                                                          2024     26102000000
                                                                                                    2023     18679000000
                                                                                                    2022     19573000000
Length: 141, dtype: object

In [21]:
apple.get_facts().to_pandas()

,namespace,fact,val,accn,end,fy,fp,form,filed,frame,start
0,dei,EntityCommonStockSharesOutstanding,8.958168e+08,0001193125-09-153165,2009-06-27,2009,Q3,10-Q,2009-07-22,CY2009Q2I,None
1,dei,EntityCommonStockSharesOutstanding,9.006785e+08,0001193125-09-214859,2009-10-16,2009,FY,10-K,2009-10-27,None,None
2,dei,EntityCommonStockSharesOutstanding,9.006785e+08,0001193125-10-012091,2009-10-16,2009,FY,10-K/A,2010-01-25,CY2009Q3I,None
3,dei,EntityCommonStockSharesOutstanding,9.067946e+08,0001193125-10-012085,2010-01-15,2010,Q1,10-Q,2010-01-25,CY2009Q4I,None
4,dei,EntityCommonStockSharesOutstanding,9.099384e+08,0001193125-10-088957,2010-04-09,2010,Q2,10-Q,2010-04-21,CY2010Q1I,None
...,...,...,...,...,...,...,...,...,...,...,...
23254,us-gaap,IncrementalCommonSharesAttributableToShareBase...,6.431200e+07,0000320193-24-000123,2024-09-28,2024,FY,10-K,2024-11-01,CY2024,2023-10-01
23255,us-gaap,OtherAssetsMiscellaneousNoncurrent,3.905300e+10,0000320193-23-000106,2022-09-24,2023,FY,10-K,2023-11-03,CY2022Q3I,None
23256,us-gaap,OtherAssetsMiscellaneousNoncurrent,4.690600e+10,0000320193-23-000106,2023-09-30,2023,FY,10-K,2023-11-03,None,None
23257,us-gaap,OtherAssetsMiscellaneousNoncurrent,4.690600e+10,0000320193-24-000123,2023-09-30,2024,FY,10-K,2024-11-01,CY2023Q3I,None
23258,us-gaap,OtherAssetsMiscellaneousNoncurrent,5.533500e+10,0000320193-24-000123,2024-09-28,2024,FY,10-K,2024-11-01,CY2024Q3I,None

In [46]:
tenK.financials.balance_sheet

                                       Apple Inc.
                               Consolidated Balance Sheets
                                         Annual

                                                                       2024        2023
 ───────────────────────────────────────────────────────────────────────────────────────
      Cash and cash equivalents                       millions       29,943      29,965
      Marketable securities                           millions       35,228      31,590
      Accounts receivable, net                        millions       33,410      29,508
      Vendor non-trade receivables                    millions       32,833      31,477
      Inventories                                     millions        7,286       6,331
      Other current assets                            millions       14,287      14,695
      Total current assets                            millions      152,987     143,566
      Marketable securities                           millions       91,479     100,544
      Property, plant and equipment, net              millions       45,680      43,715
      Other non-current assets                        millions       74,834      64,758
      Total non-current assets                        millions      211,993     209,017
    Total assets                                      millions      364,980     352,583
      Accounts payable                                millions       68,960      62,611
      Other current liabilities                       millions       78,304      58,829
      Deferred revenue                                millions        8,249       8,061
      Commercial paper                                millions        9,967       5,985
      Term debt                                       millions       10,912       9,822
      Total current liabilities                       millions      176,392     145,308
      Term debt                                       millions       85,750      95,281
      Other non-current liabilities                   millions       45,888      49,848
      Total non-current liabilities                   millions      131,638     145,129
    Total liabilities                                 millions      308,030     290,437
    Commitments and contingencies
    Common stock, shares outstanding (in shares)      thousands  15,116,786  15,550,061
    Common stock, shares issued (in shares)           thousands  15,116,786  15,550,061
      Common stock and additional paid-in capital,    millions       83,276      73,812
  $0.00001 par value: 50,400,000 shares authorized;
  15,116,786 and 15,550,061 shares issued and
  outstanding, respectively
      Accumulated deficit                             millions   (  19,154)  (     214)
      Accumulated other comprehensive loss            millions   (   7,172)  (  11,452)
      Total shareholders’ equity                      millions       56,950      62,146
    Total liabilities and shareholders’ equity        millions      364,980     352,583

In [59]:
tenK.financials.comprehensive_income

                                             Apple Inc.
                                   Comprehensive Income Statement
                                               Annual

                                                                      2024        2023        2022
 ──────────────────────────────────────────────────────────────────────────────────────────────────
  Net income                                          millions      93,736      96,995      99,803
    Change in foreign currency translation, net of    millions         395  (     765)  (   1,511)
  tax
      Change in fair value of derivative instruments  millions  (     832)         323       3,212
      Adjustment for net (gains)/losses realized and  millions  (   1,337)  (   1,717)  (   1,074)
  included in net income
      Total change in unrealized gains/losses on      millions  (   2,169)  (   1,394)       2,138
  derivative instruments
      Change in fair value of marketable debt         millions       5,850       1,563  (  12,104)
  securities
      Adjustment for net (gains)/losses realized and  millions  (     204)  (     253)  (     205)
  included in net income
      Total change in unrealized gains/losses on      millions       6,054       1,816  (  11,899)
  marketable debt securities
    Total other comprehensive income/(loss)           millions       4,280  (     343)  (  11,272)
  Total comprehensive income                          millions      98,016      96,652      88,531

In [70]:
filings = apple.get_filings(form="10-K")
latest_10k = filings.latest()

# Get XBRL data
xbrl = latest_10k.xbrl()
xbrl

╭───────────────────────────────────────────────────── XBRL ──────────────────────────────────────────────────────╮
│                   XBRL Instance                                                                                 │
│                                                                                                                 │
│   Company      Form   Period               Facts                                                                │
│  ────────────────────────────────────────────────                                                               │
│   Apple Inc.   10-K   September 28, 2024   1,045                                                                │
│                                                                                                                 │
│                           Financial Statements                                                                  │
│                                                                                                                 │
│   Name                                 Accessor                                                                 │
│  ──────────────────────────────────────────────────────────────────────                                         │
│   Balance Sheet                        financials.balance_sheet                                                 │
│   Income Statement                     financials.income                                                        │
│   Cash Flow Statement                  financials.cashflow                                                      │
│   Statement of Changes in Equity       financials.equity                                                        │
│   Statement of Comprehensive Income    financials.comprehensive_income                                          │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

In [72]:
tenK.financials.balance_sheet

                                       Apple Inc.
                               Consolidated Balance Sheets
                                         Annual

                                                                       2024        2023
 ───────────────────────────────────────────────────────────────────────────────────────
      Cash and cash equivalents                       millions       29,943      29,965
      Marketable securities                           millions       35,228      31,590
      Accounts receivable, net                        millions       33,410      29,508
      Vendor non-trade receivables                    millions       32,833      31,477
      Inventories                                     millions        7,286       6,331
      Other current assets                            millions       14,287      14,695
      Total current assets                            millions      152,987     143,566
      Marketable securities                           millions       91,479     100,544
      Property, plant and equipment, net              millions       45,680      43,715
      Other non-current assets                        millions       74,834      64,758
      Total non-current assets                        millions      211,993     209,017
    Total assets                                      millions      364,980     352,583
      Accounts payable                                millions       68,960      62,611
      Other current liabilities                       millions       78,304      58,829
      Deferred revenue                                millions        8,249       8,061
      Commercial paper                                millions        9,967       5,985
      Term debt                                       millions       10,912       9,822
      Total current liabilities                       millions      176,392     145,308
      Term debt                                       millions       85,750      95,281
      Other non-current liabilities                   millions       45,888      49,848
      Total non-current liabilities                   millions      131,638     145,129
    Total liabilities                                 millions      308,030     290,437
    Commitments and contingencies
    Common stock, shares outstanding (in shares)      thousands  15,116,786  15,550,061
    Common stock, shares issued (in shares)           thousands  15,116,786  15,550,061
      Common stock and additional paid-in capital,    millions       83,276      73,812
  $0.00001 par value: 50,400,000 shares authorized;
  15,116,786 and 15,550,061 shares issued and
  outstanding, respectively
      Accumulated deficit                             millions   (  19,154)  (     214)
      Accumulated other comprehensive loss            millions   (   7,172)  (  11,452)
      Total shareholders’ equity                      millions       56,950      62,146
    Total liabilities and shareholders’ equity        millions      364,980     352,583